<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_lastName_1</name>
   <tag></tag>
   <elementGuidId>180af942-8b7a-4412-802b-c52007b1d872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='9140d178-8053-73ac-b36f-0f169dfb6c4a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9140d178-8053-73ac-b36f-0f169dfb6c4a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;lastName&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99c587b7-5655-429b-95f7-0be89e991864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c3446705053-96 ng-untouched ng-pristine ng-invalid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>5ab9b5ef-b484-4ab3-986e-0dc8ae5a5b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3b366198-77bf-4083-8fce-b4b353b1cd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cadb2a5d-1598-4f0f-91b8-67ba8ffdd690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0145f826-3920-4bfb-bf00-af2777c47698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5da22659-ac46-45f3-a6ff-c355119ef1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>ce081a12-bf03-4d99-b3ee-349e0f6347f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-ZàèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝðÐâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸåÅæÆœŒßçÇøØ¢¿¡€\-\s]{1,35}</value>
      <webElementGuid>eb71b140-eb04-48fb-aee7-58b50fbdd36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9140d178-8053-73ac-b36f-0f169dfb6c4a</value>
      <webElementGuid>59e62ae4-7e2d-4cc5-a1b5-25e881d9f9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>09ba6e2d-140b-4427-96f7-c2ef574545b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c237fc4-8e79-4c31-8afd-9a438cadc632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9140d178-8053-73ac-b36f-0f169dfb6c4a&quot;)</value>
      <webElementGuid>f3bbfbff-8fc4-462b-925d-8bc58e5391c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='9140d178-8053-73ac-b36f-0f169dfb6c4a']</value>
      <webElementGuid>ef48b352-8104-46a6-91b2-66bcbd3c94a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-37']/div/app-step-checkout-container-body/app-checkout-step-contact-info/div/div[2]/app-customer-info-v2/div/app-dynamic-form/form/dynamic-material-form/dynamic-material-form-control[3]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>2dc7908d-c569-4686-b75b-ab71bf52b58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dynamic-material-form-control[3]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>3dbc9530-e438-4aa1-baad-546721b436b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '9140d178-8053-73ac-b36f-0f169dfb6c4a' and @name = 'lastName']</value>
      <webElementGuid>3241a6c1-813d-4c8b-be9a-1265192b6693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
