<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_phone</name>
   <tag></tag>
   <elementGuidId>7092c457-b073-4c6b-9377-6c52d1172ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='d237ec26-8080-9b4d-8187-e73b8b0a27cc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d237ec26-8080-9b4d-8187-e73b8b0a27cc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;phone&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bb68e84-1bc8-4788-8462-a1df540c22e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c3446705053-98 ng-touched ng-invalid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>5e47789b-71fe-444f-9a2e-24fa73d7a7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a4eb909b-ac97-440b-b513-63aac6aa5368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>948356e7-3b21-40f6-b831-f9b5a490cda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>477e4919-0748-427c-8846-c3a97c914527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4b315af8-e28f-40bf-95d7-ee6b6f5ea2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>1bca37db-b21c-4834-aec2-8f10fbc9e586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-mdc-error-22</value>
      <webElementGuid>97006aa6-39a2-4e4d-ba36-de97d643da8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(?:\+)?[0-9]{4,15}</value>
      <webElementGuid>a501bcf0-3284-43e7-ab99-27b1e0349a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d237ec26-8080-9b4d-8187-e73b8b0a27cc</value>
      <webElementGuid>05095d3b-5799-4566-9802-2659fa199c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>f768c4b4-85b4-444b-a959-5ed57969227f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2365d533-7761-4f4f-b2b5-8cb1671ede8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6db2d3a-e539-44ab-aeae-3d6edd8b24f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d237ec26-8080-9b4d-8187-e73b8b0a27cc&quot;)</value>
      <webElementGuid>697a91cd-95b5-4d8a-837d-a460579ee9fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d237ec26-8080-9b4d-8187-e73b8b0a27cc']</value>
      <webElementGuid>d2dbe556-bc36-4c5f-88e6-164d64efd507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-37']/div/app-step-checkout-container-body/app-checkout-step-contact-info/div/div[2]/app-customer-info-v2/div/app-dynamic-form/form/dynamic-material-form/dynamic-material-form-control[4]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>d2235315-6468-494e-8909-1bb6e7f568a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dynamic-material-form-control[4]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>91ef5010-7bb1-4bed-ab44-0d3bdce209be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'd237ec26-8080-9b4d-8187-e73b8b0a27cc' and @name = 'phone']</value>
      <webElementGuid>06d88bf2-dc17-440f-ae31-26e6870bdb39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
