<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_lastName</name>
   <tag></tag>
   <elementGuidId>5cdcec41-4456-4061-bbcb-4aaa40d320a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='2c74ff8c-c8b3-764a-bba0-c654911c1c53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2c74ff8c-c8b3-764a-bba0-c654911c1c53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;lastName&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5e4dc8d-2828-494f-96b9-06131d2fd066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c3446705053-96 ng-untouched mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>71c50e8e-a933-4489-bfae-47b41c387eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>078623cb-dffa-4546-a7e2-3bd67508bda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e7871c8-e365-4b21-93f0-d69d81f11fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9cc96884-0b7b-4cea-90e3-2078aba84b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>add10c8e-82fb-4d22-be55-562ce73dd92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>b3ca5c83-5770-4d9a-9157-9a6e7296d03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-ZàèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝðÐâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸåÅæÆœŒßçÇøØ¢¿¡€\-\s]{1,35}</value>
      <webElementGuid>321b12bc-5552-410d-a629-0c7cb185fa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2c74ff8c-c8b3-764a-bba0-c654911c1c53</value>
      <webElementGuid>1413e46b-eeb6-48a0-8a76-672e789ff9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>e6a85567-8387-4f99-aaa6-9e78417004f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb317080-5e95-43d5-a55e-90c3d19ca02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cfb762f0-b8da-4d14-b80c-d0c368b8b4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2c74ff8c-c8b3-764a-bba0-c654911c1c53&quot;)</value>
      <webElementGuid>ec104c29-b599-40ce-a395-2433b9de42de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='2c74ff8c-c8b3-764a-bba0-c654911c1c53']</value>
      <webElementGuid>3366f692-a262-41f8-948b-de188c20678d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-37']/div/app-step-checkout-container-body/app-checkout-step-contact-info/div/div[2]/app-customer-info-v2/div/app-dynamic-form/form/dynamic-material-form/dynamic-material-form-control[3]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>720ae77b-08e6-4e5a-b4e3-46a4ff3de44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dynamic-material-form-control[3]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>472b191f-ce4f-40af-848d-0519007492d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '2c74ff8c-c8b3-764a-bba0-c654911c1c53' and @name = 'lastName']</value>
      <webElementGuid>40bc3c00-4c5d-4a4f-8d36-f6c67c0832d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
