<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_firstName</name>
   <tag></tag>
   <elementGuidId>0671d2a0-7454-4214-b2b6-54819eb35191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='4e6d6a3b-9afc-f1cb-0ad5-ae649e40a82e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4e6d6a3b-9afc-f1cb-0ad5-ae649e40a82e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;firstName&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>799d455d-125e-4b75-8fd8-bd95444c6fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element ng-tns-c3446705053-94 ng-untouched ng-pristine ng-invalid mat-mdc-form-field-input-control mdc-text-field__input cdk-text-field-autofill-monitored</value>
      <webElementGuid>51a95eb0-6439-4558-b09e-3a6e7e639012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>86124856-7116-4104-a646-131aa5f21b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d68a065-7962-4a02-89cc-2c080a93733e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12ab1b1f-f610-4907-bc85-721f5ee6891e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbecac3b-200f-458d-bcdb-351fd6f5a7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>d6955df5-3054-46d8-8eb5-5882d5928576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-ZàèìòùÀÈÌÒÙáéíóúýÁÉÍÓÚÝðÐâêîôûÂÊÎÔÛãñõÃÑÕäëïöüÿÄËÏÖÜŸåÅæÆœŒßçÇøØ¢¿¡€\-\s]{2,35}</value>
      <webElementGuid>a2cb4a25-a4f7-48a2-8bb8-9ea85d8684a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4e6d6a3b-9afc-f1cb-0ad5-ae649e40a82e</value>
      <webElementGuid>bf976d95-512b-4e8e-adbc-fdc80fce95fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>f48d3ae7-7356-4879-b4e4-8727ea46bef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e804264-1e9c-469f-a0b1-b77e9b2ba67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4e6d6a3b-9afc-f1cb-0ad5-ae649e40a82e&quot;)</value>
      <webElementGuid>9baead72-416b-40f8-b0bc-c41bc44bb768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4e6d6a3b-9afc-f1cb-0ad5-ae649e40a82e']</value>
      <webElementGuid>7b806b70-c7df-40bd-84c3-961ea6920186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-37']/div/app-step-checkout-container-body/app-checkout-step-contact-info/div/div[2]/app-customer-info-v2/div/app-dynamic-form/form/dynamic-material-form/dynamic-material-form-control[2]/div/dynamic-material-input/mat-form-field/div/div[2]/div/input</value>
      <webElementGuid>4973dbc9-a004-434e-9d18-b453c62c2f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>274ea045-9d2b-4f3e-bd53-8a74c73ba927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '4e6d6a3b-9afc-f1cb-0ad5-ae649e40a82e' and @name = 'firstName']</value>
      <webElementGuid>87bd7bfe-e9c2-4c22-a319-704fde6dac3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
