<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-label_Postcode</name>
   <tag></tag>
   <elementGuidId>5b76c4ae-061e-4403-9d40-b9c0d97cba5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mat-mdc-form-field-label-20']/mat-label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.ng-tns-c3446705053-102.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-mdc-form-field-label-20 >> internal:text=&quot;Postcode&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>e0682688-acd9-42df-8afb-bef7f8dcfc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>883a72fa-df6a-fecd-a47c-d0ae8f846487</value>
      <webElementGuid>7ae4c1a4-f3d0-4f1e-a7b1-1588031e83f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c3446705053-102 ng-star-inserted</value>
      <webElementGuid>90a38b64-e008-46d2-ba2f-369bf5685304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>e14ba36d-2af3-4a56-bd6b-6eb90ed0488a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-form-field-label-20&quot;)/mat-label[@class=&quot;ng-tns-c3446705053-102 ng-star-inserted&quot;]</value>
      <webElementGuid>7468bed7-368d-447f-8d4d-e2b333a279bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mat-mdc-form-field-label-20']/mat-label</value>
      <webElementGuid>2cea4782-507e-479e-90e0-d60e33ad930e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Address'])[1]/following::mat-label[1]</value>
      <webElementGuid>18f7284a-2801-4200-b4dc-9ded4135d861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New address'])[1]/following::mat-label[1]</value>
      <webElementGuid>b1df2389-b8b2-4aa5-88a1-2e90ef5c617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter address manually'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>34fa0d2e-24c6-4c88-a044-d526f3cca722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 1'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>d5b5511e-c4a5-41c3-b59d-870132c64581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Postcode']/parent::*</value>
      <webElementGuid>2da34072-0e3b-4e6a-9d58-b465e576c2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/mat-label</value>
      <webElementGuid>1a0602e7-8398-41ec-897e-0a54caabfbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Postcode' or . = 'Postcode')]</value>
      <webElementGuid>af4442cb-38c8-4b2e-b393-71b49b673f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
