<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign InSign-Up</name>
   <tag></tag>
   <elementGuidId>5e0a4b08-7715-42bf-81fc-897d05fd1076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nv00-gnb-v3__utility-user-menu-link.loginBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='component-id']/div/div/div[6]/div[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Sign In/Sign-Up&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ae8d9ca-6a52-45d6-8df2-4aeced97d16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nv00-gnb-v3__utility-user-menu-link loginBtn</value>
      <webElementGuid>312e8579-272b-4c59-9b01-8f200344a8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>0c14f455-a8bf-48e6-bcb3-57fb6fe5b7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sign In/Sign-Up</value>
      <webElementGuid>d1a18268-7e07-4b2c-9e6a-043608a395e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>nv00_gnb-account-account</value>
      <webElementGuid>d8e82f32-24b6-4ba2-8b80-261bb8976bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>a68dc69e-1a5a-43be-b38b-654f24b6e55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>gnb</value>
      <webElementGuid>6c92188b-52a1-4b1a-be11-81284bca01b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>sign in sign up</value>
      <webElementGuid>07303cad-bab2-4027-9815-72504d61e59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-linkinfo</name>
      <type>Main</type>
      <value>https://account.samsung.com/accounts/v1/Samsung_com_UK/signInGate</value>
      <webElementGuid>6b784f94-7fdc-45d6-b6b2-3a8d269d4102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>8094bf3d-3e51-4a89-9333-e9b4fd6b0096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Sign In/Sign-Up
						</value>
      <webElementGuid>5dc3d4d6-600b-4995-8471-c55a7ea04110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-id&quot;)/div[@class=&quot;nv00-gnb-v3__wrapper&quot;]/div[@class=&quot;nv00-gnb-v3__inner-wrap&quot;]/div[@class=&quot;nv00-gnb-v3__utility-wrap&quot;]/div[@class=&quot;nv00-gnb-v3__utility before-login&quot;]/ul[@class=&quot;nv00-gnb-v3__utility-user-menu-list show&quot;]/li[@class=&quot;nv00-gnb-v3__utility-user-menu desktop-only&quot;]/a[@class=&quot;nv00-gnb-v3__utility-user-menu-link loginBtn&quot;]</value>
      <webElementGuid>c04ba56d-2a9b-4767-945d-da273e9b3cec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='component-id']/div/div/div[6]/div[3]/ul/li/a</value>
      <webElementGuid>ea4fa2cf-6633-4522-8b6f-46f5879a7828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign In/Sign-Up')])[2]</value>
      <webElementGuid>89000e19-87aa-497f-be19-d36ba05589c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::a[3]</value>
      <webElementGuid>202d6b3c-5f6a-4dad-894b-085319490ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Create a Samsung Account?'])[3]/preceding::a[1]</value>
      <webElementGuid>b1d0d521-b614-4515-ac1d-c20c365f2bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::a[2]</value>
      <webElementGuid>029b64de-daeb-4959-a3b3-0da07296cb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>51a3afb9-4efe-4100-8411-2b03354d4aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/ul/li/a</value>
      <webElementGuid>35930286-e884-4fa5-8b61-5e3a67539921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '
							Sign In/Sign-Up
						' or . = '
							Sign In/Sign-Up
						')]</value>
      <webElementGuid>d568f893-0ffb-46a2-ac3c-45f29dd356f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
