<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept All</name>
   <tag></tag>
   <elementGuidId>d8cbf060-5355-46cf-adc4-2b9ad7cbf212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#truste-consent-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='truste-consent-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Accept All&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd43d6f5-147b-4d9c-825d-279e95692294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>truste-consent-button</value>
      <webElementGuid>55a54a32-56db-4feb-907a-c864e17a3dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4eb91cba-b0e3-407d-b225-5eccdc133ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truste-button1</value>
      <webElementGuid>78ad6cab-92cb-43f0-8d7b-0eae04ca9ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept All</value>
      <webElementGuid>06204f66-5aa3-48d8-980f-791d0f9b7d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;truste-consent-button&quot;)</value>
      <webElementGuid>f1956a6d-98df-4c67-999e-2cc66e00fe55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='truste-consent-button']</value>
      <webElementGuid>2d5fba4d-ccd9-483c-a392-8efc5b11dfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='truste-consent-buttons']/button[2]</value>
      <webElementGuid>88c53dd2-7cd6-4259-bdbf-c00f854d3ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[1]/following::button[1]</value>
      <webElementGuid>a0b04f87-b60e-460b-9372-7ed98dcd7dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[3]/following::button[2]</value>
      <webElementGuid>8554beed-655b-4239-b307-192aeb0bffeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept All']/parent::*</value>
      <webElementGuid>a816d812-2684-4c6d-951c-66a115dfbb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>d4427477-d9a4-4086-b798-75828fdf294b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'truste-consent-button' and @type = 'button' and (text() = 'Accept All' or . = 'Accept All')]</value>
      <webElementGuid>2376774f-ca21-4921-9811-17858de4fe7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
