<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to basket</name>
   <tag></tag>
   <elementGuidId>f8b0d135-e634-4faa-9374-ed866e1a9184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div/div/div[2]/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cta.cta--contained.cta--black.pd19-product-card__cta--buy-now.js-cta-addon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add to basket:65” OLED S95D 4K Smart AI TV (2024)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b9c7491-3c99-44fc-bae9-5215561648f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta cta--contained cta--black pd19-product-card__cta--buy-now js-cta-addon</value>
      <webElementGuid>1783f364-d951-462d-92b3-3ad18e098e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>d331d741-18cd-46c8-b516-bb144c904a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add to basket:65” OLED S95D 4K Smart AI TV (2024)</value>
      <webElementGuid>171c6b32-b8be-4327-b126-408b7a7ac0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cart</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e68182e2-0b42-44fe-a567-6f33cbe01612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcode</name>
      <type>Main</type>
      <value>QE65S95DATXXU</value>
      <webElementGuid>c3503d79-a17e-4a53-a4c1-7efdc24c999c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-desktop-src</name>
      <type>Main</type>
      <value>//images.samsung.com/is/image/samsung/p6pim/uk/qe65s95datxxu/gallery/uk-oled-s95d-qe65s95datxxu-thumb-544695781?$216_216_PNG$</value>
      <webElementGuid>f791a7aa-3689-41e6-b21e-ca08d8109127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mobile-src</name>
      <type>Main</type>
      <value>//images.samsung.com/is/image/samsung/p6pim/uk/qe65s95datxxu/gallery/uk-oled-s95d-qe65s95datxxu-thumb-544695781?$UX_EXT2_PNG$</value>
      <webElementGuid>3e6ae629-2ab0-4d40-82aa-0505d99e71e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-img-alt</name>
      <type>Main</type>
      <value>QE55S95DATXXU </value>
      <webElementGuid>9b00ed9c-6808-48cf-952b-a52749933a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price-text</name>
      <type>Main</type>
      <value>From £61.09/mo  for 36 mos at 0% APR or £2,199.00</value>
      <webElementGuid>6ab07f2c-9233-4707-a6ef-cf8c8cf76def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>2199</value>
      <webElementGuid>f5264ea2-d703-4430-9ed0-69a32b3bf66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price-month</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>befea201-67fe-4416-be85-c50dfe4149a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-name</name>
      <type>Main</type>
      <value>65” OLED S95D 4K Smart AI TV (2024)</value>
      <webElementGuid>01f929d8-3d23-4a93-9437-d592fb69dc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-save-price</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>48b23720-7d60-45e6-9006-49080bb3ad85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-price</name>
      <type>Main</type>
      <value>2199</value>
      <webElementGuid>7af8c230-b863-41cc-86d8-87fe5c53a1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link_info</name>
      <type>Main</type>
      <value>https://shop.samsung.com/uk/cart/</value>
      <webElementGuid>b02415b4-e982-4da1-be38-d2d512d1bb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pimsubtype</name>
      <type>Main</type>
      <value>oled tv </value>
      <webElementGuid>aea2161d-9232-4acf-8396-060ae88d64e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvitype</name>
      <type>Main</type>
      <value>tv</value>
      <webElementGuid>834b71fb-9906-4364-a374-937c4f3ae9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvisubtype</name>
      <type>Main</type>
      <value>oled</value>
      <webElementGuid>5e484efc-c0be-44ab-a400-2db669e96dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelrevenue</name>
      <type>Main</type>
      <value>2299</value>
      <webElementGuid>f5a9fe29-f52d-4417-9c5c-402cf74a6f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelqty</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>46bb5c5c-1cbc-4404-8a9a-0e3b1431ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcurrency</name>
      <type>Main</type>
      <value>GBP</value>
      <webElementGuid>a15e6a65-2034-4c6d-98f8-71f5174b0ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>QE65S95DAT</value>
      <webElementGuid>3f6b5baf-a8ce-4d83-a6ec-c88594ab87dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modeldisplay</name>
      <type>Main</type>
      <value>65” OLED S95D 4K Smart AI TV (2024)</value>
      <webElementGuid>1aa62bb5-d8e8-4ae4-b9e1-e7246726db48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelprice</name>
      <type>Main</type>
      <value>2299</value>
      <webElementGuid>6a91bf18-9289-4d4a-b9a8-e004d2e030a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>pd19_product finder-product finder-buy now / pre order-ecommerce1</value>
      <webElementGuid>734e0347-ab6c-4460-8932-7ddf2d930d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>ecommerce</value>
      <webElementGuid>758b3ce1-6d95-424d-a134-45e6760d5a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>addToCart</value>
      <webElementGuid>9f2344b1-daee-4f55-88f7-1aa02fd23c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>pf product card:buy now</value>
      <webElementGuid>09d9a3e8-981b-4d15-8ab0-28b74aa5c4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Add to basket
											</value>
      <webElementGuid>0cb7fd24-0536-429e-9de2-0d6b2348e586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;root responsivegrid&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;responsivegrid aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;pd-g-product-finder-ux2 aem-GridColumn aem-GridColumn--default--12&quot;]/section[@class=&quot;pd19-product-finder pd19-product-finder--filter-sticky js-pfv2-finder pd19-product-finder--top-sticky&quot;]/div[@class=&quot;pd19-product-finder__result&quot;]/div[@class=&quot;pd19-product-finder__inner&quot;]/div[@class=&quot;pd19-product-finder__contents&quot;]/div[@class=&quot;pd19-product-card&quot;]/div[@class=&quot;pd19-product-card__list js-pfv2-content-wrap&quot;]/div[@class=&quot;pd19-product-card__item js-pfv2-product-card pd19-product-card__item--active pd19-product-card__item--start&quot;]/div[@class=&quot;pd19-product-card__wrapper&quot;]/div[@class=&quot;pd19-product-card__content-wrap&quot;]/div[@class=&quot;pd19-product-card__cta-wrap&quot;]/a[@class=&quot;cta cta--contained cta--black pd19-product-card__cta--buy-now js-cta-addon&quot;]</value>
      <webElementGuid>ad70b0d7-5e7a-43bb-a653-b57c1eb55d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discountprice</name>
      <type>Main</type>
      <value>2199</value>
      <webElementGuid>2edf2ee6-edb1-446b-9233-5329a44e17ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div/div/div[2]/div[6]/a</value>
      <webElementGuid>775895ea-3fdf-4514-9119-57f1aa19083c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add to basket')]</value>
      <webElementGuid>efb37761-3645-478c-9c6b-19e1c16ed418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£2,299.00'])[1]/following::a[1]</value>
      <webElementGuid>65a3f2b8-84ab-465c-a185-f86028cc0777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::a[1]</value>
      <webElementGuid>d05e9760-a7a7-48c3-b5c9-0223ae52539c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compare'])[1]/preceding::a[2]</value>
      <webElementGuid>e1516729-214e-446d-b1e3-bab9744ccf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to basket']/parent::*</value>
      <webElementGuid>434d57ef-5bdd-412c-80a7-2cab54863296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[6]</value>
      <webElementGuid>fa5e9434-2137-4d6b-84b4-1e78d3123269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/a</value>
      <webElementGuid>2a3cf57d-45b4-4ba7-b8f8-9739d450e4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '
												Add to basket
											' or . = '
												Add to basket
											')]</value>
      <webElementGuid>85ee5933-2a19-45c0-80e0-2a1517ea0f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£3,799.00'])[1]/following::a[1]</value>
      <webElementGuid>546b11f2-72eb-41bd-8fd4-8ecb94c762df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
