<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_77selected</name>
   <tag></tag>
   <elementGuidId>b83d284f-2a20-4024-8175-c10feaa0d388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;77 selected&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>206314a2-1e18-4300-a577-be24d0691a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3db242f7-e42f-4fb1-8598-46a4766c4bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-selector-v3__size js-pfv2-product-fmychip</value>
      <webElementGuid>e23fe0ad-ec43-4acf-b0fb-99f125a8ccb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-chiptype</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>5b40a234-4216-47dd-ace9-0ec2e31b1447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modeli</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3d38db3d-ffba-4804-afee-cbb44984ba01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>pd19_product finder-product finder-option-option_click</value>
      <webElementGuid>747b2327-bd15-4376-a508-abf3bd459f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>option click</value>
      <webElementGuid>f23154df-d1d5-4e71-a591-5244d4e9986b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>pf product card</value>
      <webElementGuid>b962b657-0767-465d-aca3-1c8cd0ab523d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>tv size:77</value>
      <webElementGuid>275fce2b-3ae8-4e9f-9286-81b644992b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcode</name>
      <type>Main</type>
      <value>QE77S95DATXXU</value>
      <webElementGuid>0e200ce3-6e96-4e12-8e1c-b288b26f8a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>QE77S95DAT</value>
      <webElementGuid>2333c45f-c858-44b7-b0c9-b48d1482f898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										77
										selected
									</value>
      <webElementGuid>07ac0401-d2dd-45a3-8739-4ed7d631f8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;root responsivegrid&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;responsivegrid aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;pd-g-product-finder-ux2 aem-GridColumn aem-GridColumn--default--12&quot;]/section[@class=&quot;pd19-product-finder pd19-product-finder--filter-sticky js-pfv2-finder pd19-product-finder--top-sticky&quot;]/div[@class=&quot;pd19-product-finder__result&quot;]/div[@class=&quot;pd19-product-finder__inner&quot;]/div[@class=&quot;pd19-product-finder__contents&quot;]/div[@class=&quot;pd19-product-card&quot;]/div[@class=&quot;pd19-product-card__list js-pfv2-content-wrap&quot;]/div[@class=&quot;pd19-product-card__item js-pfv2-product-card pd19-product-card__item--active pd19-product-card__item--start&quot;]/div[@class=&quot;pd19-product-card__wrapper&quot;]/div[@class=&quot;pd19-product-card__content-wrap&quot;]/div[@class=&quot;pd19-product-card__option-selector-wrap&quot;]/div[@class=&quot;option-selector-v3&quot;]/div[@class=&quot;option-selector-v3__wrap option-selector-v3__wrap--capacity&quot;]/ul[@class=&quot;option-selector-v3__list&quot;]/li[@class=&quot;option-selector-v3__item&quot;]/button[@class=&quot;option-selector-v3__size js-pfv2-product-fmychip&quot;]</value>
      <webElementGuid>e7e55f23-d04e-401a-97e5-2eb401ae265f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>c7693c33-0655-46e3-9815-3079fc05ca3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div/div/div[2]/div[4]/div/div/ul/li[3]/button</value>
      <webElementGuid>438f5540-9596-402f-b451-46578b1549f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selected'])[1]/following::button[2]</value>
      <webElementGuid>8a17e5ed-3dda-423c-a876-bfe13445d65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::button[3]</value>
      <webElementGuid>64b3a57c-d866-4655-9285-245799618a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[3]/button</value>
      <webElementGuid>8c927e54-77ad-4df2-8ee0-d53654e56a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
										77
										selected
									' or . = '
										77
										selected
									')]</value>
      <webElementGuid>2750b8dc-c442-403a-a4a3-cc4ea5edaf54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
