<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_77</name>
   <tag></tag>
   <elementGuidId>b602e5cc-befd-4037-bd6d-9410b41ae807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div/div/div[2]/div[4]/div/div/ul/li[3]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;77 selected&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3cdf225-60d4-40bb-b345-a31e8753d836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-selector-v3__size-text</value>
      <webElementGuid>192a6b1d-8832-4c4f-bb45-37d8cb0bcca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>77</value>
      <webElementGuid>3f3183e8-1d43-4db6-b100-143979a8a4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;root responsivegrid&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;responsivegrid aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;pd-g-product-finder-ux2 aem-GridColumn aem-GridColumn--default--12&quot;]/section[@class=&quot;pd19-product-finder pd19-product-finder--filter-sticky js-pfv2-finder pd19-product-finder--top-sticky&quot;]/div[@class=&quot;pd19-product-finder__result&quot;]/div[@class=&quot;pd19-product-finder__inner&quot;]/div[@class=&quot;pd19-product-finder__contents&quot;]/div[@class=&quot;pd19-product-card&quot;]/div[@class=&quot;pd19-product-card__list js-pfv2-content-wrap&quot;]/div[@class=&quot;pd19-product-card__item js-pfv2-product-card pd19-product-card__item--active pd19-product-card__item--start&quot;]/div[@class=&quot;pd19-product-card__wrapper&quot;]/div[@class=&quot;pd19-product-card__content-wrap&quot;]/div[@class=&quot;pd19-product-card__option-selector-wrap&quot;]/div[@class=&quot;option-selector-v3&quot;]/div[@class=&quot;option-selector-v3__wrap option-selector-v3__wrap--capacity&quot;]/ul[@class=&quot;option-selector-v3__list&quot;]/li[@class=&quot;option-selector-v3__item&quot;]/button[@class=&quot;option-selector-v3__size js-pfv2-product-fmychip&quot;]/span[@class=&quot;option-selector-v3__size-text&quot;]</value>
      <webElementGuid>ea86bfd3-124b-480a-baa6-3b3e440754ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div/div/div[2]/div[4]/div/div/ul/li[3]/button/span</value>
      <webElementGuid>1e688f80-6f3a-488b-8481-5de8e928036e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selected'])[1]/following::span[2]</value>
      <webElementGuid>2e588f2d-ccb7-47d1-88e7-bab6bd5afa01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::span[5]</value>
      <webElementGuid>2a8cf2a7-2412-4274-b1bb-2f73c03a2480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selected'])[2]/preceding::span[1]</value>
      <webElementGuid>35a38ec6-8f60-44bd-8679-588d61a00ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='77']/parent::*</value>
      <webElementGuid>d84f7fcb-22f1-4775-8174-5c5bc6d529c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[3]/button/span</value>
      <webElementGuid>d8f231bd-387e-475d-8669-998ede87cceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '77' or . = '77')]</value>
      <webElementGuid>f4e7b5f9-8998-4f13-81d2-397269c6aeda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
