<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Appliances</name>
   <tag></tag>
   <elementGuidId>425ad0fa-20af-462e-858a-b5a2fecbafdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='component-id']/div/div/div[5]/ul/li[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.nv00-gnb-v3__l0-menu.focus > button.nv00-gnb-v3__l0-menu-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Appliances&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>141a490f-df01-46bc-97c3-993fdef8c763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nv00-gnb-v3__l0-menu-btn</value>
      <webElementGuid>9ac59298-7a53-453b-94be-5aadd3fd771e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>86dee0e8-e4ba-49a1-a4fa-121a340c7a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36f2abdf-51b8-4595-a94e-b2ddd0fcdb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aca52e5a-9401-4855-86f8-cec860561b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>nv00_gnb-home-l0-navigation2</value>
      <webElementGuid>6cf6ef33-fc6c-420d-a2a6-67f00ddde0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>navigation</value>
      <webElementGuid>91ab0804-16a3-4c37-b699-e051c27a389c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>gnb</value>
      <webElementGuid>092998d2-0d67-415c-9ab1-e3331d6ee921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>appliances</value>
      <webElementGuid>17e80622-5181-4f36-967c-9e06996b2d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Appliances
                
                    
                
            </value>
      <webElementGuid>72e0e32d-1e26-4471-afb4-1b4825af3f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-id&quot;)/div[@class=&quot;nv00-gnb-v3__wrapper&quot;]/div[@class=&quot;nv00-gnb-v3__inner-wrap&quot;]/div[@class=&quot;nv00-gnb-v3__l0-menu-wrap&quot;]/ul[@class=&quot;nv00-gnb-v3__l0-menu-list left-menu&quot;]/li[@class=&quot;nv00-gnb-v3__l0-menu focus&quot;]/button[@class=&quot;nv00-gnb-v3__l0-menu-btn&quot;]</value>
      <webElementGuid>66ca0daf-a8bd-43df-ae32-0610b0c34105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='component-id']/div/div/div[5]/ul/li[4]/button</value>
      <webElementGuid>0e3a7200-d9de-45c7-9f20-825f1f6a28d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soundbar Buying Guide'])[1]/following::button[1]</value>
      <webElementGuid>0f9dbd33-aa22-4ae0-91f8-4b61ffea9313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Buying Guide'])[1]/following::button[1]</value>
      <webElementGuid>cd99840b-b3a1-480b-aa91-d68c82b34f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Refrigerators'])[1]/preceding::button[1]</value>
      <webElementGuid>4c11ab9b-414f-49a2-a3be-e222cde5e63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='French Door'])[1]/preceding::button[1]</value>
      <webElementGuid>60e2292f-9c46-47fb-b3e1-a5ca609bfc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Appliances']/parent::*</value>
      <webElementGuid>bb0b3d7f-9e4c-47f8-b7bf-7c110bf52392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>17747a0e-24d7-457c-813e-3d5998bbb933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                Appliances
                
                    
                
            ' or . = '
                Appliances
                
                    
                
            ')]</value>
      <webElementGuid>7ba4b337-33f1-4e3b-82fc-ff8be3ed71cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
