<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_httpsshop.samsung.comukcart_icon</name>
   <tag></tag>
   <elementGuidId>a8e1957d-485d-4235-9a5c-abb3e46200c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nv00-gnb-v3__utility-btn.mobile-only.loginBtn > svg.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Manage Account&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>22578418-8a72-4c67-a3a0-7ac73c2cc36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>0ac3782d-2785-4b92-832e-de777b764501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0df2da0e-d504-4932-9d9e-2dd9c9039311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a636b355-59d5-47d9-9f73-e03557b25d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>1e049fd7-ab5f-439a-b7c6-fb9a60f292d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>1af5ed2f-c36f-4b32-b88e-96a3cc90f170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 96 96</value>
      <webElementGuid>fb18a29b-0a36-486e-b12d-d1a9170bb625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-id&quot;)/div[@class=&quot;nv00-gnb-v3__wrapper&quot;]/div[@class=&quot;nv00-gnb-v3__inner-wrap&quot;]/div[@class=&quot;nv00-gnb-v3__utility-wrap&quot;]/div[@class=&quot;nv00-gnb-v3__utility before-login&quot;]/a[@class=&quot;nv00-gnb-v3__utility-btn mobile-only loginBtn&quot;]/svg[@class=&quot;icon&quot;]</value>
      <webElementGuid>329de26b-c573-4836-b14a-2e9630f6798f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/following::*[name()='svg'][2]</value>
      <webElementGuid>efbdee0c-27af-43c4-8024-437f59c918a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In/Sign-Up'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>74eb55af-335d-4667-a1d4-631d9e58d563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Create a Samsung Account?'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>ea6aaf7a-efc1-41b1-8736-1b3619054815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
