<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to basket</name>
   <tag></tag>
   <elementGuidId>cc701ba9-14ce-4a4d-a33c-d9ff43fcf798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cta.cta--contained.cta--black.pd19-product-card__cta--buy-now.js-pfv2-buy-now</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add to basket:Samsung Jet™ 75E Pet Cordless Stick Vacuum Cleaner, Max 200W Suction Power with Pet Tool - Teal Mint&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>727b038f-11c8-4292-bae3-2b8d58e7c163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta cta--contained cta--black pd19-product-card__cta--buy-now js-pfv2-buy-now</value>
      <webElementGuid>ce85ae30-0efb-4997-baf1-d342fc3db359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>cc6d9efd-41f8-4c30-a3f8-52394dfbf0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add to basket:Samsung Jet™ 75E Pet Cordless Stick Vacuum Cleaner, Max 200W Suction Power with Pet Tool - Teal Mint</value>
      <webElementGuid>8cb3807f-b95b-46df-8716-3e8dd90bf894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cart</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed780e01-645b-4e93-a114-e66ea28e568f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sku-code</name>
      <type>Main</type>
      <value>VS20B75AGR1/EU</value>
      <webElementGuid>98fbd023-d662-4028-85c1-9b198ac22428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link_info</name>
      <type>Main</type>
      <value>https://shop.samsung.com/uk/cart/</value>
      <webElementGuid>b819e447-77be-4638-8516-5db40adb09c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pimsubtype</name>
      <type>Main</type>
      <value>stick</value>
      <webElementGuid>3a3c026d-9d0b-4b3b-a68f-623c34ea1523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvitype</name>
      <type>Main</type>
      <value>vacuum cleaner</value>
      <webElementGuid>da0cb86f-c54b-4ba1-b349-5f19f189e256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvisubtype</name>
      <type>Main</type>
      <value>stick / handy</value>
      <webElementGuid>bd57aebe-e64f-43d9-b1f5-c44b7b9dd268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelrevenue</name>
      <type>Main</type>
      <value>429</value>
      <webElementGuid>51aa588b-638a-4f57-b625-c1d30bb45e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelqty</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>282493ab-83a1-4ad9-848d-ef4a7ae04ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcurrency</name>
      <type>Main</type>
      <value>GBP</value>
      <webElementGuid>f8430855-d890-44df-b266-22030b550914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcode</name>
      <type>Main</type>
      <value>VS20B75AGR1/EU</value>
      <webElementGuid>29979e58-20d9-4cd8-94dc-fd27c7f931c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>VS20B75AGR1</value>
      <webElementGuid>46cb71a4-c20e-410a-8856-6a968ffdc698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modeldisplay</name>
      <type>Main</type>
      <value>Samsung Jet™ 75E Pet Cordless Stick Vacuum Cleaner, Max 200W Suction Power with Pet Tool - Teal Mint</value>
      <webElementGuid>1b39a466-59ca-4bf6-a3e0-44f7c5d2bf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelprice</name>
      <type>Main</type>
      <value>429</value>
      <webElementGuid>488815d8-9819-486a-8295-7c815f9cc55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-discountprice</name>
      <type>Main</type>
      <value>299</value>
      <webElementGuid>21acfea9-dbb6-407e-8b31-1d38126ec4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>pd19_product finder-product finder-buy now / pre order-ecommerce1</value>
      <webElementGuid>0fc5da76-e0fb-4ae0-9b76-5f42f9c46f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>ecommerce</value>
      <webElementGuid>48a5f8b7-b35e-4526-a7dd-6ed8b93357e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>addToCart</value>
      <webElementGuid>090fc0d4-afbd-44ee-b171-1bb17cfbb236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>pf product card:add to cart</value>
      <webElementGuid>fbbae96b-1a40-4ece-9c05-50ef9f99fa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
														Add to basket
													</value>
      <webElementGuid>e0484eb1-ad74-4896-8d2f-e1f9c59d064f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;root responsivegrid&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;responsivegrid aem-GridColumn aem-GridColumn--default--12&quot;]/div[@class=&quot;aem-Grid aem-Grid--12 aem-Grid--default--12&quot;]/div[@class=&quot;pd-g-product-finder-ux2 aem-GridColumn aem-GridColumn--default--12&quot;]/section[@class=&quot;pd19-product-finder pd19-product-finder--filter-sticky js-pfv2-finder pd19-product-finder--top-sticky&quot;]/div[@class=&quot;pd19-product-finder__result&quot;]/div[@class=&quot;pd19-product-finder__inner&quot;]/div[@class=&quot;pd19-product-finder__contents&quot;]/div[@class=&quot;pd19-product-card&quot;]/div[@class=&quot;pd19-product-card__list js-pfv2-content-wrap&quot;]/div[@class=&quot;pd19-product-card__item js-pfv2-product-card pd19-product-card__item--active pd19-product-card__item--start&quot;]/div[@class=&quot;pd19-product-card__wrapper&quot;]/div[@class=&quot;pd19-product-card__content-wrap&quot;]/div[@class=&quot;pd19-product-card__cta-wrap&quot;]/a[@class=&quot;cta cta--contained cta--black pd19-product-card__cta--buy-now js-pfv2-buy-now&quot;]</value>
      <webElementGuid>76d112f0-8e72-4a8a-9094-c8affdca0688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[4]/div/div/div/div/section/div/div[2]/div[2]/div/div/div[2]/div/div[2]/div[6]/a</value>
      <webElementGuid>2b5243a7-50be-4f52-929b-a0923501b821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add to basket')]</value>
      <webElementGuid>2c676a6e-359c-42e5-ac00-9115bd01c570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£429.00'])[1]/following::a[1]</value>
      <webElementGuid>96917fcd-29da-41d5-8862-db339723cf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[4]/preceding::a[1]</value>
      <webElementGuid>36894e74-af43-436b-9b5e-719bbfcfc9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compare'])[2]/preceding::a[2]</value>
      <webElementGuid>4cc888ac-55a4-44bf-af58-25c543af9bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to basket']/parent::*</value>
      <webElementGuid>ec32b18d-95f3-4c37-8baa-1781fb35fbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[7]</value>
      <webElementGuid>c4a14ced-e74f-4838-992c-4e10b56cef25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[6]/a</value>
      <webElementGuid>2505e4b2-5eed-4cd4-a0db-e97830732a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '
														Add to basket
													' or . = '
														Add to basket
													')]</value>
      <webElementGuid>d40726df-4db0-4f3a-a4fa-2d6fe7bc16da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
