<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send code</name>
   <tag></tag>
   <elementGuidId>33838c9d-0c6d-4c8b-9cce-874ee5a62d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Send code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00ff1118-1d94-4829-be74-34203ea93cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSms</value>
      <webElementGuid>bbec4389-4691-462d-a9fe-63cab2e193c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>one-cancel one-button</value>
      <webElementGuid>70b3987c-e4d1-4d4f-97b5-50ef286c9170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2177684-2787-4569-b6a3-4ad3d856d579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>btnSms();</value>
      <webElementGuid>dcf12c37-8033-411a-bc94-f8d45e97b633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>isResendBtnDisabled</value>
      <webElementGuid>7e5bd0b8-6fa0-4c5f-b9a9-9396aec22797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Send code
                  </value>
      <webElementGuid>04c2c68c-3c5c-42ce-afe3-7263b9fc6ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSms&quot;)</value>
      <webElementGuid>33acc818-a24e-47c5-b99c-79c5a053b6da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSms']</value>
      <webElementGuid>c83410cc-53a3-4625-ace2-7f81ae797fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two-step verification'])[2]/following::button[1]</value>
      <webElementGuid>54f29734-3bcf-45ad-958c-20c21ecd08a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Text message'])[1]/following::button[1]</value>
      <webElementGuid>ff7eeab4-d1e6-41ff-8570-0a756500b90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two-step verification'])[3]/preceding::button[1]</value>
      <webElementGuid>5c4be23a-83d7-4efc-9edf-490f3a4e5d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification code'])[1]/preceding::button[1]</value>
      <webElementGuid>3ced03ab-cd02-4d49-b1b1-ba4d65631856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send code']/parent::*</value>
      <webElementGuid>ca1f5a13-d5ff-47ed-a92c-d7e334df944a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b34c3308-9482-4f73-8fe3-539bd678ee6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSms' and @type = 'button' and (text() = '
                    Send code
                  ' or . = '
                    Send code
                  ')]</value>
      <webElementGuid>c2dce72c-b4d0-4e0f-af4f-adf7747625d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
