<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Galaxy S25 Ultra</name>
   <tag></tag>
   <elementGuidId>e1f5926a-5245-4885-a4a6-0a3571459ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchResultContainer']/div[2]/div[2]/div/div[2]/div/ul/li[2]/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#searchResultContainer >> internal:text=&quot;Galaxy S25 Ultra&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fbb5430-6041-4d18-bc89-d115f9b19ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aisearch-product__name</value>
      <webElementGuid>e8de9fc4-ac2e-4df2-96cc-9c29d9fe2ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/uk/smartphones/galaxy-s/galaxy-s25-ultra-titanium-silverblue-512gb-sm-s938bzbgeub/</value>
      <webElementGuid>4609f51e-b8d2-4c3c-a386-585efca55fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href-target</name>
      <type>Main</type>
      <value>/uk/smartphones/galaxy-s/galaxy-s25-ultra-titanium-silverblue-512gb-sm-s938bzbgeub/</value>
      <webElementGuid>be291fd1-20cd-432b-992f-d05582b19f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcode</name>
      <type>Main</type>
      <value>SM-S938BZBGEUB</value>
      <webElementGuid>57ef71e8-5bfe-485e-b52b-82d96b416597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>SM-S938B/DS</value>
      <webElementGuid>dff1801c-a1e6-4a0b-953c-3249edd0db55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>srd18_sr page-aisearch-product-search1</value>
      <webElementGuid>8ce75914-7589-41ae-9fcd-8f6f6efbc1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>bb4a1ec5-05bc-485d-a4c6-06955e76142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>search result click</value>
      <webElementGuid>0cf4b6e9-ace7-44aa-b67d-d49fbfa83af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>products:product click:result2</value>
      <webElementGuid>dcb4ff3e-ed1d-4a53-942e-a85f9ef3c833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Galaxy S25 Ultra</value>
      <webElementGuid>a1df03b8-3d33-4b3e-90fe-ecc5bda405cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResultContainer&quot;)/div[@class=&quot;aisearch__result&quot;]/div[@class=&quot;aisearch__wrap&quot;]/div[@class=&quot;aisearch__inner&quot;]/div[@class=&quot;aisearch__contents&quot;]/div[@class=&quot;aisearch__list-wrap&quot;]/ul[@class=&quot;aisearch__list&quot;]/li[@class=&quot;aisearch__item aisearch__item--active aisearch__item--start&quot;]/div[@class=&quot;aisearch-product&quot;]/div[@class=&quot;aisearch-product__name-wrap&quot;]/a[@class=&quot;aisearch-product__name&quot;]</value>
      <webElementGuid>c63b5134-a0de-4ff5-a9c9-28e7ebdc1eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchResultContainer']/div[2]/div[2]/div/div[2]/div/ul/li[2]/div/div[3]/a</value>
      <webElementGuid>04408fb9-1b60-4e6a-8aa0-0d0faa481c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Galaxy S25 Ultra')])[2]</value>
      <webElementGuid>90b51887-e0c2-4526-bc36-255487814fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[5]/following::a[2]</value>
      <webElementGuid>f22264f0-9a61-41a5-bad0-f6d5abf51be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find support'])[1]/following::a[2]</value>
      <webElementGuid>bc57ea42-130f-41f6-a97a-303977f08aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(9999+)'])[2]/preceding::a[1]</value>
      <webElementGuid>715c982e-ae19-4150-92b3-bd18d85a61db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/uk/smartphones/galaxy-s/galaxy-s25-ultra-titanium-silverblue-512gb-sm-s938bzbgeub/')])[2]</value>
      <webElementGuid>4b148b8c-f98e-4cc9-910a-83510fbefd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[3]/a</value>
      <webElementGuid>3d4143d7-114c-4148-9e33-123c03c22998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/uk/smartphones/galaxy-s/galaxy-s25-ultra-titanium-silverblue-512gb-sm-s938bzbgeub/' and (text() = 'Galaxy S25 Ultra' or . = 'Galaxy S25 Ultra')]</value>
      <webElementGuid>3e85d725-020e-404b-9827-6215d54586bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
