<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Form_search</name>
   <tag></tag>
   <elementGuidId>f6e11e9a-96ed-43e6-ba76-28b18b86c422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gnb-search-keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gnb-search-keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd72fcc0-5d23-4dea-9cbe-c82a48dc13ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6ada8dc-5e5b-42dc-b386-01124d0d31f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>fc5875f3-99c2-4d60-bb6d-e1128dcc4119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>srd19-gnb-search__input</value>
      <webElementGuid>0016d93e-6e91-429c-a5c9-8481d8a92228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>6c4ec5ff-13fb-4ecc-941e-20c95bdca3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gnb-search-keyword</value>
      <webElementGuid>b28c763e-2667-48d3-99ea-2cc2b2866c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search </value>
      <webElementGuid>a5037779-e72b-4b04-94d3-9e04d69df44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gnb-search-keyword&quot;)</value>
      <webElementGuid>fe6e5056-270c-42cc-a84b-dac366cf2cc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gnb-search-keyword']</value>
      <webElementGuid>221375ae-5a0e-4cc8-b878-1b96b34d939d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/section[3]/div[2]/form/fieldset/div/input</value>
      <webElementGuid>dfe35cad-d3d6-45f4-85bb-cb0c9ef5b19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>73df508a-3aa9-437f-80e0-b86e06f3eced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @id = 'gnb-search-keyword' and @placeholder = 'Search ']</value>
      <webElementGuid>c7b12305-fcb3-4157-9129-1583c8f7fd60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
