<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue to delivery options</name>
   <tag></tag>
   <elementGuidId>bfcdceb9-a804-4af1-bd80-5a2708f978c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-37']/div/app-step-checkout-container-body/app-checkout-step-contact-info/div/div[6]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.primary.pill-btn.pill-btn--blue.customer-details--continue-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue to delivery options&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2371ef72-4045-402f-9f87-630863f4728d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary pill-btn pill-btn--blue customer-details--continue-btn</value>
      <webElementGuid>048ae2ee-d10e-4171-8fea-f65429852836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-an-tr</name>
      <type>Main</type>
      <value>checkout-step-ecommerce</value>
      <webElementGuid>c33a4eda-4895-480d-ac08-f74ad0357c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-an-la</name>
      <type>Main</type>
      <value>customer details:Continue to delivery options</value>
      <webElementGuid>c08d17c6-4af9-454a-ae9e-0efaeb322624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue to delivery options </value>
      <webElementGuid>6336e922-3691-49e8-afbc-d02f475bd25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-37&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c779108242-84&quot;]/app-step-checkout-container-body[@class=&quot;step-checkout-container-body ng-star-inserted&quot;]/app-checkout-step-contact-info[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;checkout-customer-details-form&quot;]/div[@class=&quot;customer-details-btn--container&quot;]/button[@class=&quot;button primary pill-btn pill-btn--blue customer-details--continue-btn&quot;]</value>
      <webElementGuid>b27580d6-6e44-4625-851b-65c467e272ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-37']/div/app-step-checkout-container-body/app-checkout-step-contact-info/div/div[6]/button</value>
      <webElementGuid>6055d7f5-d367-48fe-909f-e960d1194647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Billing Address'])[1]/following::button[1]</value>
      <webElementGuid>afa862e8-77f3-4f72-80cc-afc795940ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Order'])[1]/preceding::button[1]</value>
      <webElementGuid>3043d0be-06dc-4209-9ad7-8f53a70f808b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/button</value>
      <webElementGuid>fca84cdb-8df3-4d17-a7ab-eed13fc637e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Continue to delivery options ' or . = ' Continue to delivery options ')]</value>
      <webElementGuid>b7c5e7e1-3fe3-48bd-864a-08f0df6937c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
