<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>860fce97-fc58-466e-b265-fd6f147a3241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-qty-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;+&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8eabd91-3018-4af7-885c-e4597fb353c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95d0cdf9-85c0-42ce-8e9e-f4abf06ae09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c030a179-ca8a-4029-ac3b-0de6ee680ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-qty-plus</value>
      <webElementGuid>b0e5a077-1f85-4412-bfc8-3998ac92c0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcode</name>
      <type>Main</type>
      <value>VS20B75AGR1/EU</value>
      <webElementGuid>2f37dc82-1e14-4262-ad02-f6d45f263707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>VS20B75AGR1</value>
      <webElementGuid>9bc59e2b-8f45-4e27-b82f-c1ecb987ade5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modeldisplay</name>
      <type>Main</type>
      <value>Samsung Jet™ 75E Pet Cordless Stick Vacuum Cleaner, Max 200W Suction Power with Pet Tool - Teal Mint</value>
      <webElementGuid>92fddbf2-7a04-4c2b-9493-8868832bded5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelprice</name>
      <type>Main</type>
      <value>299</value>
      <webElementGuid>5228cd1d-8141-463c-afab-1eadf9a194bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelrevenue</name>
      <type>Main</type>
      <value>299</value>
      <webElementGuid>cf8a14da-9dfd-484c-b029-ea498e93596e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelunit</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>02013f84-83ed-41c6-837c-376d67b005f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvitype</name>
      <type>Main</type>
      <value>Vacuum Cleaner</value>
      <webElementGuid>38b0612e-fb9b-488a-be83-3825a28d89d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvisubtype</name>
      <type>Main</type>
      <value>Stick / Handy</value>
      <webElementGuid>3cbbdc4b-9fde-42a3-a546-e0ccfc73f87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pimsubtype</name>
      <type>Main</type>
      <value>Stick</value>
      <webElementGuid>cc56233b-2ac3-4c83-ba6f-5009e40beaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-an-tr</name>
      <type>Main</type>
      <value>move-to-cart-option</value>
      <webElementGuid>dd2b181b-c620-4ba8-bc13-5f4d15dec5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-an-la</name>
      <type>Main</type>
      <value>plus button</value>
      <webElementGuid>4a3ce50f-a616-495f-9f56-5f66aae6a815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> +
</value>
      <webElementGuid>03915d1c-3baf-4545-812e-e8ca28be336e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;uk&quot;]/cx-storefront[@class=&quot;v2 CartPageTemplateV2 stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;CartPageTemplateV2 ng-star-inserted&quot;]/cx-page-slot[@class=&quot;TokoLeftContent has-components ng-star-inserted&quot;]/cx-cart-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cart-details-wrapper ng-star-inserted&quot;]/cx-cart-item-list-v2[1]/div[@class=&quot;order-summary-menu&quot;]/div[2]/div[@class=&quot;cart-item-list ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/cx-cart-item-v2[1]/div[@class=&quot;cart-item ng-star-inserted&quot;]/div[@class=&quot;cart-item__container-right cart-item__price ng-star-inserted&quot;]/div[@class=&quot;cart-item__image-container-right&quot;]/div[@class=&quot;cart-item__quantity ng-star-inserted&quot;]/cart-item-counter[@class=&quot;text-super-class&quot;]/button[@class=&quot;btn-qty-plus&quot;]</value>
      <webElementGuid>564bc6c0-57e7-43c4-8420-a1697f0a51a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>d9caa8d5-1f27-4a7a-866b-0caecc134c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[1]</value>
      <webElementGuid>96e4128b-79a7-481e-ba94-98adb1ff3ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£429.00'])[1]/following::button[3]</value>
      <webElementGuid>1f21c9e9-7f98-44d3-85ff-9f9e4ffa2b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trade Up'])[1]/preceding::button[1]</value>
      <webElementGuid>528316f6-3f8e-4d32-a13e-b62bf00da1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Up to £50.00 off your order when you Trade Up your old appliance'])[1]/preceding::button[1]</value>
      <webElementGuid>a685b3e6-771d-4c6d-be5d-f4f5d723f22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>f281b0d3-1549-454c-a5d6-024dfba01b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cart-item-counter/button[2]</value>
      <webElementGuid>65a1d122-773f-4f9b-9b48-aff3bd1a92b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' +
' or . = ' +
')]</value>
      <webElementGuid>78a4d395-fc2b-4aac-b804-1969b3d05186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
